<?php
/**
 * @file
 * theme_cbf2019_features.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function theme_cbf2019_features_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: menu-cbf-2019-main-menu_about-us:node/3670.
  $menu_links['menu-cbf-2019-main-menu_about-us:node/3670'] = array(
    'menu_name' => 'menu-cbf-2019-main-menu',
    'link_path' => 'node/3670',
    'router_path' => 'node/%',
    'link_title' => 'About us',
    'options' => array(
      'identifier' => 'menu-cbf-2019-main-menu_about-us:node/3670',
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
  );
  // Exported menu link: menu-cbf-2019-main-menu_activities:node/3686.
  $menu_links['menu-cbf-2019-main-menu_activities:node/3686'] = array(
    'menu_name' => 'menu-cbf-2019-main-menu',
    'link_path' => 'node/3686',
    'router_path' => 'node/%',
    'link_title' => 'Activities',
    'options' => array(
      'identifier' => 'menu-cbf-2019-main-menu_activities:node/3686',
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 1,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
  );
  // Exported menu link: menu-cbf-2019-main-menu_blog:articles.
  $menu_links['menu-cbf-2019-main-menu_blog:articles'] = array(
    'menu_name' => 'menu-cbf-2019-main-menu',
    'link_path' => 'articles',
    'router_path' => 'articles',
    'link_title' => 'Blog',
    'options' => array(
      'identifier' => 'menu-cbf-2019-main-menu_blog:articles',
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
  );
  // Exported menu link: menu-cbf-2019-main-menu_resources:library.
  $menu_links['menu-cbf-2019-main-menu_resources:library'] = array(
    'menu_name' => 'menu-cbf-2019-main-menu',
    'link_path' => 'library',
    'router_path' => 'library',
    'link_title' => 'Resources',
    'options' => array(
      'identifier' => 'menu-cbf-2019-main-menu_resources:library',
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
  );
  // Exported menu link: menu-cbf-2019-main-menu_whats-on:node/3686.
  $menu_links['menu-cbf-2019-main-menu_whats-on:node/3686'] = array(
    'menu_name' => 'menu-cbf-2019-main-menu',
    'link_path' => 'node/3686',
    'router_path' => 'node/%',
    'link_title' => 'What\'s on',
    'options' => array(
      'identifier' => 'menu-cbf-2019-main-menu_whats-on:node/3686',
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Exported menu link: menu-cbf-2019-plus-menu_about-us:node/3670.
  $menu_links['menu-cbf-2019-plus-menu_about-us:node/3670'] = array(
    'menu_name' => 'menu-cbf-2019-plus-menu',
    'link_path' => 'node/3670',
    'router_path' => 'node/%',
    'link_title' => 'About us',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-cbf-2019-plus-menu_about-us:node/3670',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
  );
  // Exported menu link: menu-cbf-2019-plus-menu_activities:node/3686.
  $menu_links['menu-cbf-2019-plus-menu_activities:node/3686'] = array(
    'menu_name' => 'menu-cbf-2019-plus-menu',
    'link_path' => 'node/3686',
    'router_path' => 'node/%',
    'link_title' => 'Activities',
    'options' => array(
      'identifier' => 'menu-cbf-2019-plus-menu_activities:node/3686',
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 1,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
  );
  // Exported menu link: menu-cbf-2019-plus-menu_blog:articles.
  $menu_links['menu-cbf-2019-plus-menu_blog:articles'] = array(
    'menu_name' => 'menu-cbf-2019-plus-menu',
    'link_path' => 'articles',
    'router_path' => 'articles',
    'link_title' => 'Blog',
    'options' => array(
      'identifier' => 'menu-cbf-2019-plus-menu_blog:articles',
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
  );
  // Exported menu link: menu-cbf-2019-plus-menu_get-involved:node/3786.
  $menu_links['menu-cbf-2019-plus-menu_get-involved:node/3786'] = array(
    'menu_name' => 'menu-cbf-2019-plus-menu',
    'link_path' => 'node/3786',
    'router_path' => 'node/%',
    'link_title' => 'Get involved',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-cbf-2019-plus-menu_get-involved:node/3786',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
  );
  // Exported menu link: menu-cbf-2019-plus-menu_resources:library.
  $menu_links['menu-cbf-2019-plus-menu_resources:library'] = array(
    'menu_name' => 'menu-cbf-2019-plus-menu',
    'link_path' => 'library',
    'router_path' => 'library',
    'link_title' => 'Resources',
    'options' => array(
      'identifier' => 'menu-cbf-2019-plus-menu_resources:library',
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
  );
  // Exported menu link: menu-cbf-2019-plus-menu_whats-on:node/3686.
  $menu_links['menu-cbf-2019-plus-menu_whats-on:node/3686'] = array(
    'menu_name' => 'menu-cbf-2019-plus-menu',
    'link_path' => 'node/3686',
    'router_path' => 'node/%',
    'link_title' => 'What\'s on',
    'options' => array(
      'identifier' => 'menu-cbf-2019-plus-menu_whats-on:node/3686',
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Exported menu link: menu-third-space-main-menu_about-us:<front>.
  $menu_links['menu-third-space-main-menu_about-us:<front>'] = array(
    'menu_name' => 'menu-third-space-main-menu',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'About us',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-third-space-main-menu_about-us:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('About us');
  t('Activities');
  t('Blog');
  t('Get involved');
  t('Resources');
  t('What\'s on');

  return $menu_links;
}
